{
 "title": "dashboard_Site1",
 "description": "tableau de bord du site 1",
 "tags": [
  "solar data from raspberry #site1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "voltage",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"voltage\") FROM \"solar_panel\" WHERE \"location\" = 'site_1' AND $timeFilter GROUP BY time($interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"current\") FROM \"solar_panel\" WHERE \"location\" = 'site_1' AND $timeFilter GROUP BY time($interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT mean(\"energy\") FROM \"solar_panel\" WHERE \"location\" = 'site_1' AND $timeFilter GROUP BY time($interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT mean(\"temperature\") FROM \"solar_panel\" WHERE \"location\" = 'site_1' AND $timeFilter GROUP BY time($interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "kWh",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_panel",
     "query": "SELECT mean(\"kWh\") FROM \"solar_panel\" WHERE \"location\" = 'site_1' AND $timeFilter GROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"humidity\") FROM \"solar_panel\" WHERE \"location\" = 'site_1' AND $timeFilter GROUP BY time($interval) fill(null)\n"
    }
   ]
  }
 ]
}